_target_: spil.models.perceptual_encoders.concat_encoders_mix.ConcatEncodersMix

_recursive_: false

defaults:
 - rgb_static: default
 - rgb_gripper: default
 - depth_static: none
 - depth_gripper: none
 - proprio: none
 - tactile: none
