defaults:
  - perceptual_encoder: gripper_cam_seg
  # - perceptual_encoder: gripper_cam
  - plan_proposal: default
  - plan_recognition: transformers_seg
  - distribution:  discrete
  - visual_goal: default
  - language_goal: default
  - language_encoder: default
  - language_encoder2: default
  - action_decoder: skill
  - optimizer: adam
  - lr_scheduler: constant
  - bc_z_lang_decoder: none
  - mia_lang_discriminator: none
  - proj_vis_lang: default
  - /annotations@val_instructions: new_playtable_validation

_target_: spil.models.spil.Spil
_recursive_: false

kl_beta: ${loss.kl_beta}
kl_balancing_mix: ${loss.kl_balancing_mix}
state_recons: false
state_recon_beta: ${loss.state_recon_beta}
use_bc_z_auxiliary_loss: false
bc_z_auxiliary_loss_beta: ${loss.bc_z_auxiliary_loss_beta}
use_mia_auxiliary_loss: false
mia_auxiliary_loss_beta: ${loss.mia_auxiliary_loss_beta}
replan_freq: 30
use_clip_auxiliary_loss: true
clip_auxiliary_loss_beta: ${loss.clip_auxiliary_loss_beta}

use_temporal_contrastive_loss: true
use_action_chunk: true
temporal_contrastive_loss_beta: ${loss.temporal_contrastive_loss_beta}
use_lang_vis_temporal_contrastive_loss: true
lang_vis_temporal_contrastive_loss_beta: ${loss.lang_vis_temporal_contrastive_loss_beta}
temperature: 1.1
