wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1704466301.668509
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.18
      5: 0.13.11
      8:
      - 5
